name: automerge
# on:
#   pull_request:
#     types:
#       - labeled
#       - unlabeled
#       - synchronize
#       - opened
#       - edited
#       - ready_for_review
#       - reopened
#       - unlocked
#   pull_request_review:
#     types:
#       - submitted
#   status: {}
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: rebase
          UPDATE_METHOD: rebase