on: push 
    
name: Generate Changelog

jobs:
  build:
    name: Generate Changelog
    runs-on: ubuntu-latest
    env:
      DEPLOY_USER: "ExtendedXmlSerializer Automation via GitHub Action"
      DEPLOY_EMAIL: "ExtendedXmlSerializer@users.noreply.github.com"
    steps:
      - uses: actions/checkout@master #
      - name: Create CHANGELOG.md
        run: |
             .\.build\Generate-Changelog.ps1 ${{ github.event.repository.owner.name }} ${{ github.event.repository.name }} | Out-File "CHANGELOG.md"
             
             git submodule update --init
             git submodule update --rebase --remote
             
             Copy-Item CHANGELOG.md .\documentation\conceptual\documents\CHANGELOG.md -Force
        shell: pwsh
      - name: Push Submodule
        run: |
             cd .\documentation\conceptual\documents
             dir
             git config user.email $env:DEPLOY_EMAIL
             git config user.name $env:DEPLOY_USER
             git add -A
             git diff-index --quiet HEAD | Out-Null
             git status
             if(!$?)
             {
                git commit -m "Updating CHANGELOG"
                # git push                
             }             
        shell: pwsh
#      - name: Commit files
#        run: |
#             git config user.email $env:DEPLOY_EMAIL
#             git config user.name $env:DEPLOY_USER
#             git add -A
#             git diff-index --quiet HEAD | Out-Null
#             if(!$?)
#             {
#                git commit -m "Updating CHANGELOG"
#             }
#        shell: pwsh
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
