name: CI

# on: [push]
on:
  release:
    types: [published, unpublished, edited]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Hello World!
      run: |
           Write-Host "Hello World Are you There?!"
      shell: pwsh
